name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Show GitHub version
      run: git version
    - name: GITHUB_ACTOR
      run: echo $GITHUB_ACTOR
    - name: INPUT_REPO
      run: echo $INPUT_REPO
    - name: git tag
      run:  |
        git tag 0.0.1
        git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$INPUT_REPO.git" origin --tags
