name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        echo RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
